version: '3'
services:
  db:
    image: mysql:5.6
    container_name: mysql-5.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: board
      MYSQL_USER: jspexam
      MYSQL_PASSWORD: jsppw
    ports:
      - "3306:3306"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 9080:8080

  web:
    image: tomcat:8.5
    container_name: tomcat-8.5
    environment:
      JDBC_URL: jdbc:mysql://db:3306/board
      JDBC_USER: jspexam
      JDBC_PASS: jsppw
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    links:
      - db
    restart: always
